version: "3.7"
services:
  portainer:
    image: portainer/portainer:latest
    container_name: portainer_utils
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    ports:
      - "9015:9000"
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_utils
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: vitor.lima@msn.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  portainer-data:
  pgadmin-data: