version: '3.5'
services:
  postgres:
    image: debezium/postgres:13-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/docker/master/postgres13/data:/var/lib/postgresql/data/pgdata:rw
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data/pgdata
  redis:
    container_name: redis
    image: redis:6.2.3-alpine3.13
    ports:
      - "6379:6379"
    volumes:
      - /var/docker/master/redis/data:/data:rw
    restart: always
  rabbit:
    image: rabbitmq:3.8.16-management-alpine
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - /var/docker/master/rabbitmq/data/:/var/lib/rabbitmq:rw
      - /var/docker/master/rabbitmq/logs/:/var/log/rabbitmq:rw
networks:
  default:
    external:
      name: services